In [18]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [19]:
import pandas as pd
import course.utils.paths as path

from sklearn.linear_model import RANSACRegressor, HuberRegressor
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [20]:
data_DIR = path.data_raw_dir('happiness_modified.csv')
dataset = pd.read_csv(data_DIR)
display(dataset)

,country,rank,score,high,low,gdp,family,lifexp,freedom,generosity,corruption,dystopia
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182
...,...,...,...,...,...,...,...,...,...,...,...,...
162,H,163,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
163,I,164,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
164,J,165,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
165,K,166,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
166,L,167,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [21]:
X = dataset.drop(['country', 'rank', 'score', 'high', 'low'], axis=1)
y = dataset['score']
X_train, X_test, y_train, y_trest = train_test_split(X, y, test_size=0.3, random_state=42)

In [23]:
estimators = {
    'SVR' : SVR(gamma='auto', C=1.0, epsilon=0.1),
    'RANSAC' : RANSACRegressor(),
    'HUBER' : HuberRegressor(epsilon=1.35)
}

In [24]:
for name, estimator in estimators.items():
    estimator.fit(X_train, y_train)
    prediction = estimator.predict(X_test)
    
    print('-'*10)
    print(name)
    print('MSE: ', mean_squared_error(y_trest, prediction))

----------
SVR
MSE:  0.0067738484344523515
----------
RANSAC
MSE:  9.410090618166122e-08
----------
HUBER
MSE:  1.0362420243340522e-07