In [24]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [25]:
import pandas as pd
import numpy as np
import course.utils.paths as path


from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score, KFold

In [26]:
data_DIR = path.data_raw_dir('happiness.csv')
dataset = pd.read_csv(data_DIR)
display(dataset)

,country,rank,score,high,low,gdp,family,lifexp,freedom,generosity,corruption,dystopia
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182
...,...,...,...,...,...,...,...,...,...,...,...,...
150,Rwanda,151,3.471,3.543030,3.398970,0.368746,0.945707,0.326425,0.581844,0.252756,0.455220,0.540061
151,Syria,152,3.462,3.663669,3.260331,0.777153,0.396103,0.500533,0.081539,0.493664,0.151347,1.061574
152,Tanzania,153,3.349,3.461430,3.236570,0.511136,1.041990,0.364509,0.390018,0.354256,0.066035,0.621130
153,Burundi,154,2.905,3.074690,2.735310,0.091623,0.629794,0.151611,0.059901,0.204435,0.084148,1.683024
154,Central African Republic,155,2.693,2.864884,2.521116,0.000000,0.000000,0.018773,0.270842,0.280876,0.056565,2.066005

In [27]:
X = dataset.drop(['country', 'rank', 'score', 'high', 'low'], axis=1)
y = dataset['score']

In [28]:
estimator = DecisionTreeRegressor()
score = cross_val_score(estimator, X, y, cv=4, scoring='neg_mean_squared_error')
print(score)
print('Score mean:', np.abs(np.mean(score)))

[-0.93791479 -0.48906908 -0.66864787 -0.87093549]
Score mean: 0.7416418069627178

In [29]:
kf = KFold(n_splits=4, shuffle=True, random_state=42)
for train, test in kf.split(dataset):
    print('Training set:', train)
    print('Test set:', test)

Training set: [  0   1   2   3   4   5   6   7   8  10  11  13  14  16  17  20  21  22
  23  25  27  28  32  33  34  35  36  37  38  39  40  41  43  44  46  47
  48  49  50  52  53  54  55  56  57  58  59  61  62  63  64  66  67  70
  71  72  73  74  76  77  79  80  83  85  87  88  89  91  92  94  97  98
  99 100 101 102 103 104 105 106 107 108 110 111 112 113 114 115 116 119
 120 121 123 124 125 127 128 129 130 132 134 135 136 139 140 141 143 144
 145 146 148 149 150 151 152 154]
Test set: [  9  12  15  18  19  24  26  29  30  31  42  45  51  60  65  68  69  75
  78  81  82  84  86  90  93  95  96 109 117 118 122 126 131 133 137 138
 142 147 153]
Training set: [  1   2   3   5   6   7   8   9  12  13  14  15  17  18  19  20  21  24
  26  29  30  31  33  34  35  37  38  42  43  45  46  47  48  49  50  51
  52  53  54  57  58  59  60  61  62  63  65  68  69  70  71  72  73  74
  75  77  78  80  81  82  83  84  86  87  88  89  90  91  92  93  94  95
  96  98  99 100 102 103 105 106 107 109 111 112 114 115 116 117 118 120
 121 122 125 126 127 128 129 130 131 132 133 135 136 137 138 139 140 142
 145 147 148 149 150 152 153 154]
Test set: [  0   4  10  11  16  22  23  25  27  28  32  36  39  40  41  44  55  56
  64  66  67  76  79  85  97 101 104 108 110 113 119 123 124 134 141 143
 144 146 151]
Training set: [  0   1   2   4   6   9  10  11  12  14  15  16  18  19  20  21  22  23
  24  25  26  27  28  29  30  31  32  36  37  39  40  41  42  44  45  48
  50  51  52  54  55  56  57  58  60  63  64  65  66  67  68  69  71  72
  74  75  76  78  79  81  82  84  85  86  87  88  90  92  93  95  96  97
  99 100 101 102 103 104 106 107 108 109 110 113 115 116 117 118 119 120
 121 122 123 124 126 128 129 130 131 133 134 135 137 138 141 142 143 144
 145 146 147 149 151 152 153 154]
Test set: [  3   5   7   8  13  17  33  34  35  38  43  46  47  49  53  59  61  62
  70  73  77  80  83  89  91  94  98 105 111 112 114 125 127 132 136 139
 140 148 150]
Training set: [  0   3   4   5   7   8   9  10  11  12  13  15  16  17  18  19  22  23
  24  25  26  27  28  29  30  31  32  33  34  35  36  38  39  40  41  42
  43  44  45  46  47  49  51  53  55  56  59  60  61  62  64  65  66  67
  68  69  70  73  75  76  77  78  79  80  81  82  83  84  85  86  89  90
  91  93  94  95  96  97  98 101 104 105 108 109 110 111 112 113 114 117
 118 119 122 123 124 125 126 127 131 132 133 134 136 137 138 139 140 141
 142 143 144 146 147 148 150 151 153]
Test set: [  1   2   6  14  20  21  37  48  50  52  54  57  58  63  71  72  74  87
  88  92  99 100 102 103 106 107 115 116 120 121 128 129 130 135 145 149
 152 154]